"use client";

import { useEffect, useMemo, useState } from "react";

type Client = { id: string; businessName: string };
type SeoTask = {
  id: string;
  task: string;
  category: string;
  priority: string;
  completed: boolean;
  completedAt: string | null;
  createdAt: string;
  pageUrl: string | null;
  issueType: string | null;
  recommendation: string | null;
};

const PRIORITY_COLOR: Record<string, string> = {
  HIGH: "bg-red-50 text-red-700 border-red-100",
  MEDIUM: "bg-amber-50 text-amber-700 border-amber-100",
  LOW: "bg-slate-50 text-slate-700 border-slate-200",
};

const CATEGORIES = ["GBP", "Technical", "Content", "Citations", "Off-Page", "Reviews", "SEO Audit", "general"];
const STATUS_FILTERS = ["Open", "Done", "All"];
const PRIORITY_FILTERS = ["All", "HIGH", "MEDIUM", "LOW"];
const MODE_FILTERS = ["All", "Automated", "Semi-Automated", "Manual"];
const MODE_COLOR: Record<string, string> = {
  Automated: "bg-emerald-50 text-emerald-700 border-emerald-100",
  "Semi-Automated": "bg-blue-50 text-blue-700 border-blue-100",
  Manual: "bg-slate-50 text-slate-700 border-slate-200",
};

function summarizeTask(task: SeoTask) {
  if (task.issueType && task.pageUrl) return task.issueType;
  return task.task;
}

function pageTopic(url: string | null) {
  if (!url) return "this page";
  try {
    const parsed = new URL(url);
    const parts = parsed.pathname.split("/").filter(Boolean);
    if (parts.length === 0) return "the homepage";
    return parts[parts.length - 1].replace(/[-_]/g, " ").replace(/\.(html|php|aspx)$/i, "").trim() || "this page";
  } catch {
    return "this page";
  }
}

function generateFix(task: SeoTask, businessName: string) {
  const topic = pageTopic(task.pageUrl);
  const issue = (task.issueType || task.task).toLowerCase();

  if (issue.includes("missing meta description")) {
    return `Suggested meta description: ${businessName} provides ${topic} services and solutions with reliable support. Learn more, compare options, and contact the team today.`;
  }

  if (issue.includes("missing h1")) {
    const title = topic === "the homepage" ? businessName : `${topic.charAt(0).toUpperCase()}${topic.slice(1)} Services`;
    return `Suggested H1: ${title}`;
  }

  if (issue.includes("title")) {
    const title = topic === "the homepage" ? `${businessName} | Services and Solutions` : `${topic.charAt(0).toUpperCase()}${topic.slice(1)} | ${businessName}`;
    return `Suggested title tag: ${title}`;
  }

  if (issue.includes("canonical")) {
    return `Add a self-referencing canonical tag in the page head: <link rel="canonical" href="${task.pageUrl || "https://example.com/page"}" />`;
  }

  if (issue.includes("sitemap")) {
    return "Create a sitemap.xml containing all canonical, indexable URLs, add it to robots.txt, and submit it in Google Search Console.";
  }

  if (issue.includes("robots")) {
    return "Create a robots.txt file that allows important public pages and references the XML sitemap location.";
  }

  if (issue.includes("non-200")) {
    return "Check whether the URL should exist. Restore the page, add a 301 redirect to the closest active page, or remove internal links pointing to it.";
  }

  if (issue.includes("alt")) {
    return "Add short, descriptive alt text to each image. Describe the image naturally and include service/product context only when accurate.";
  }

  if (task.recommendation) return task.recommendation;
  return "Review the page, apply the recommended SEO fix, verify the page works correctly, then mark this task as done.";
}

function taskMode(task: SeoTask) {
  const text = `${task.issueType ?? ""} ${task.task} ${task.category}`.toLowerCase();

  if (
    text.includes("sitemap") ||
    text.includes("robots") ||
    text.includes("canonical") ||
    text.includes("schema")
  ) return "Automated";

  if (
    text.includes("missing meta") ||
    text.includes("title") ||
    text.includes("h1") ||
    text.includes("alt") ||
    text.includes("content") ||
    text.includes("blog") ||
    text.includes("faq") ||
    text.includes("description")
  ) return "Semi-Automated";

  return "Manual";
}

function modeDescription(mode: string) {
  if (mode === "Automated") return "Can be generated by BizAutomatrix, then applied after website/CMS access is connected.";
  if (mode === "Semi-Automated") return "BizAutomatrix can create the wording or fix plan, but admin should review before publishing.";
  return "Requires admin/client action, login, verification, or platform approval.";
}

function modeActionLabel(mode: string) {
  if (mode === "Automated") return "Prepare for Apply";
  if (mode === "Semi-Automated") return "Review Suggested Fix";
  return "Manual Follow-up";
}

function SummaryCard({ label, value, tone }: { label: string; value: string | number; tone: "blue" | "green" | "amber" | "slate" }) {
  const styles = {
    blue: "bg-blue-50 border-blue-100 text-blue-700",
    green: "bg-green-50 border-green-100 text-green-700",
    amber: "bg-amber-50 border-amber-100 text-amber-700",
    slate: "bg-slate-50 border-slate-200 text-slate-700",
  };

  return (
    <div className={`rounded-lg border p-4 ${styles[tone]}`}>
      <p className="text-xs font-semibold uppercase tracking-wide opacity-80">{label}</p>
      <p className="mt-1 text-2xl font-bold">{value}</p>
    </div>
  );
}

export default function AdminSeoTasks() {
  const [clients, setClients] = useState<Client[]>([]);
  const [selectedClient, setSelectedClient] = useState("");
  const [tasks, setTasks] = useState<SeoTask[]>([]);
  const [loading, setLoading] = useState(false);
  const [newTask, setNewTask] = useState("");
  const [newCat, setNewCat] = useState("general");
  const [newPriority, setNewPriority] = useState("MEDIUM");
  const [seeding, setSeeding] = useState(false);
  const [statusFilter, setStatusFilter] = useState("Open");
  const [priorityFilter, setPriorityFilter] = useState("All");
  const [categoryFilter, setCategoryFilter] = useState("All");
  const [modeFilter, setModeFilter] = useState("All");
  const [search, setSearch] = useState("");
  const [expandedTaskId, setExpandedTaskId] = useState<string | null>(null);
  const [generatedFixes, setGeneratedFixes] = useState<Record<string, string>>({});
  const [selectedTaskIds, setSelectedTaskIds] = useState<Set<string>>(new Set());
  const [bulkReviewPlan, setBulkReviewPlan] = useState("");

  useEffect(() => {
    fetch("/api/admin/seo-tasks").then(r => r.json()).then(d => setClients(d.clients ?? []));
  }, []);

  useEffect(() => {
    if (!selectedClient) return;
    fetch(`/api/admin/seo-tasks?clientId=${selectedClient}`)
      .then(r => r.json())
      .then(d => {
        setTasks(d.tasks ?? []);
        setLoading(false);
      });
  }, [selectedClient]);

  function handleClientChange(clientId: string) {
    setSelectedClient(clientId);
    setTasks([]);
    setExpandedTaskId(null);
    setGeneratedFixes({});
    setSelectedTaskIds(new Set());
    setBulkReviewPlan("");
    setStatusFilter("Open");
    setPriorityFilter("All");
    setCategoryFilter("All");
    setModeFilter("All");
    setLoading(Boolean(clientId));
  }

  async function refreshTasks() {
    if (!selectedClient) return;
    const d = await (await fetch(`/api/admin/seo-tasks?clientId=${selectedClient}`)).json();
    setTasks(d.tasks ?? []);
  }

  async function seedDefaults() {
    setSeeding(true);
    const d = await (await fetch("/api/admin/seo-tasks", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ clientId: selectedClient, seedDefaults: true }),
    })).json();
    setTasks(d.tasks ?? []);
    setSeeding(false);
  }

  async function addTask() {
    if (!newTask.trim()) return;
    await fetch("/api/admin/seo-tasks", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ clientId: selectedClient, task: newTask.trim(), category: newCat, priority: newPriority }),
    });
    setNewTask("");
    await refreshTasks();
  }

  async function toggleTask(id: string, completed: boolean) {
    await fetch("/api/admin/seo-tasks", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, completed }),
    });
    setTasks(prev => prev.map(t => t.id === id ? { ...t, completed, completedAt: completed ? new Date().toISOString() : null } : t));
  }

  async function deleteTask(id: string) {
    if (!confirm("Delete this task?")) return;
    await fetch(`/api/admin/seo-tasks?id=${id}`, { method: "DELETE" });
    setTasks(prev => prev.filter(t => t.id !== id));
  }

  function generateTaskFix(task: SeoTask) {
    const clientName = clients.find(c => c.id === selectedClient)?.businessName ?? "the business";
    setGeneratedFixes(prev => ({ ...prev, [task.id]: generateFix(task, clientName) }));
    setExpandedTaskId(task.id);
  }

  function toggleSelectedTask(id: string, selected: boolean) {
    setSelectedTaskIds(prev => {
      const next = new Set(prev);
      if (selected) next.add(id);
      else next.delete(id);
      return next;
    });
  }

  function selectTasksByMode(mode: string) {
    const ids = filteredTasks
      .filter(task => !task.completed && taskMode(task) === mode)
      .map(task => task.id);
    setSelectedTaskIds(new Set(ids));
    setBulkReviewPlan("");
  }

  function selectVisibleTasks() {
    setSelectedTaskIds(new Set(filteredTasks.filter(task => !task.completed).map(task => task.id)));
    setBulkReviewPlan("");
  }

  function clearSelectedTasks() {
    setSelectedTaskIds(new Set());
    setBulkReviewPlan("");
  }

  function generateBulkReviewPlan() {
    const clientName = clients.find(c => c.id === selectedClient)?.businessName ?? "the business";
    const selectedTasks = tasks.filter(task => selectedTaskIds.has(task.id));
    const fixes = selectedTasks.reduce<Record<string, SeoTask[]>>((acc, task) => {
      const mode = taskMode(task);
      acc[mode] = [...(acc[mode] ?? []), task];
      return acc;
    }, {});

    const plan = Object.entries(fixes)
      .map(([mode, modeTasks]) => {
        const rows = modeTasks.slice(0, 30).map((task, index) => {
          const fix = generateFix(task, clientName);
          return `${index + 1}. ${summarizeTask(task)}\n   Page: ${task.pageUrl || "N/A"}\n   Next step: ${modeActionLabel(mode)}\n   Suggested fix: ${fix}`;
        }).join("\n\n");
        const more = modeTasks.length > 30 ? `\n\n   ${modeTasks.length - 30} more ${mode.toLowerCase()} tasks selected. Use filters to review the remaining items.` : "";
        return `${mode} (${modeTasks.length})\n${modeDescription(mode)}\n\n${rows}${more}`;
      })
      .join("\n\n---\n\n");

    const generated = selectedTasks.reduce<Record<string, string>>((acc, task) => {
      acc[task.id] = generateFix(task, clientName);
      return acc;
    }, {});

    setGeneratedFixes(prev => ({ ...prev, ...generated }));
    setBulkReviewPlan(plan || "No tasks selected.");
    setExpandedTaskId(selectedTasks[0]?.id ?? null);
  }

  async function markSelectedDone() {
    const ids = [...selectedTaskIds];
    if (ids.length === 0) return;
    if (!confirm(`Mark ${ids.length} selected task${ids.length === 1 ? "" : "s"} as done?`)) return;
    await Promise.all(ids.map(id => fetch("/api/admin/seo-tasks", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, completed: true }),
    })));
    const doneAt = new Date().toISOString();
    setTasks(prev => prev.map(task => selectedTaskIds.has(task.id) ? { ...task, completed: true, completedAt: doneAt } : task));
    clearSelectedTasks();
  }

  const categories = useMemo(() => ["All", ...Array.from(new Set(tasks.map(t => t.category))).sort()], [tasks]);
  const completed = tasks.filter(t => t.completed).length;
  const open = tasks.length - completed;
  const highOpen = tasks.filter(t => !t.completed && t.priority === "HIGH").length;
  const progress = tasks.length > 0 ? Math.round((completed / tasks.length) * 100) : 0;
  const automated = tasks.filter(t => taskMode(t) === "Automated" && !t.completed).length;
  const semiAutomated = tasks.filter(t => taskMode(t) === "Semi-Automated" && !t.completed).length;
  const manual = tasks.filter(t => taskMode(t) === "Manual" && !t.completed).length;
  const filteredTasks = tasks.filter(task => {
    if (statusFilter === "Open" && task.completed) return false;
    if (statusFilter === "Done" && !task.completed) return false;
    if (priorityFilter !== "All" && task.priority !== priorityFilter) return false;
    if (categoryFilter !== "All" && task.category !== categoryFilter) return false;
    if (modeFilter !== "All" && taskMode(task) !== modeFilter) return false;
    const haystack = [task.task, task.pageUrl, task.issueType, task.recommendation, task.category].filter(Boolean).join(" ").toLowerCase();
    return haystack.includes(search.toLowerCase());
  });
  const selectedTasks = tasks.filter(task => selectedTaskIds.has(task.id));
  const selectedAutomated = selectedTasks.filter(task => taskMode(task) === "Automated").length;
  const selectedSemiAutomated = selectedTasks.filter(task => taskMode(task) === "Semi-Automated").length;
  const selectedManual = selectedTasks.filter(task => taskMode(task) === "Manual").length;

  return (
    <div>
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-gray-900">SEO Tasks</h1>
        <p className="text-gray-500 mt-1">Review generated issues, create suggested fixes, and mark completed work.</p>
      </div>

      <div className="bg-white rounded-lg border border-gray-200 p-5 mb-6">
        <label className="text-sm font-medium text-gray-700 block mb-2">Select Client</label>
        <select
          value={selectedClient}
          onChange={e => handleClientChange(e.target.value)}
          className="w-full sm:w-80 px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500"
        >
          <option value="">Choose a client...</option>
          {clients.map(c => <option key={c.id} value={c.id}>{c.businessName}</option>)}
        </select>
      </div>

      {selectedClient && (
        <div className="space-y-6">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <SummaryCard label="Open Tasks" value={open} tone="amber" />
            <SummaryCard label="High Priority" value={highOpen} tone="blue" />
            <SummaryCard label="Completed" value={completed} tone="green" />
            <SummaryCard label="Progress" value={`${progress}%`} tone="slate" />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <button
              onClick={() => setModeFilter(modeFilter === "Automated" ? "All" : "Automated")}
              className={`text-left rounded-lg border p-4 transition-colors ${modeFilter === "Automated" ? "border-emerald-300 bg-emerald-50" : "border-gray-200 bg-white hover:bg-gray-50"}`}
            >
              <p className="text-xs font-semibold uppercase text-emerald-700">Automated</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{automated}</p>
              <p className="mt-1 text-xs text-gray-500">Can be generated/applied after site access is connected.</p>
            </button>
            <button
              onClick={() => setModeFilter(modeFilter === "Semi-Automated" ? "All" : "Semi-Automated")}
              className={`text-left rounded-lg border p-4 transition-colors ${modeFilter === "Semi-Automated" ? "border-blue-300 bg-blue-50" : "border-gray-200 bg-white hover:bg-gray-50"}`}
            >
              <p className="text-xs font-semibold uppercase text-blue-700">Semi-Automated</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{semiAutomated}</p>
              <p className="mt-1 text-xs text-gray-500">Generate fix, review, then publish manually or later via API.</p>
            </button>
            <button
              onClick={() => setModeFilter(modeFilter === "Manual" ? "All" : "Manual")}
              className={`text-left rounded-lg border p-4 transition-colors ${modeFilter === "Manual" ? "border-slate-300 bg-slate-50" : "border-gray-200 bg-white hover:bg-gray-50"}`}
            >
              <p className="text-xs font-semibold uppercase text-slate-700">Manual</p>
              <p className="mt-1 text-2xl font-bold text-gray-900">{manual}</p>
              <p className="mt-1 text-xs text-gray-500">Needs login, verification, client decision, or off-site action.</p>
            </button>
          </div>

          <div className="bg-white rounded-lg border border-gray-200 p-5">
            <div className="flex justify-between items-center mb-2">
              <span className="text-sm font-medium text-gray-700">Overall Progress</span>
              <span className="text-sm font-bold text-gray-900">{completed}/{tasks.length} done</span>
            </div>
            <div className="w-full h-3 bg-gray-100 rounded-full overflow-hidden">
              <div className="h-full bg-green-500 rounded-full transition-all" style={{ width: `${progress}%` }} />
            </div>
          </div>

          <div className="bg-white rounded-lg border border-gray-200 p-5">
            <div className="flex flex-wrap gap-3 mb-4">
              <button onClick={seedDefaults} disabled={seeding}
                className="px-4 py-2 bg-gray-800 text-white rounded-lg text-sm font-medium hover:bg-gray-900 disabled:opacity-50 transition-colors">
                {seeding ? "Loading..." : "Load Default SEO Tasks"}
              </button>
            </div>
            <div className="flex flex-wrap gap-3">
              <input type="text" placeholder="Custom task..." value={newTask}
                onChange={e => setNewTask(e.target.value)}
                className="flex-1 min-w-60 px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500" />
              <select value={newCat} onChange={e => setNewCat(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                {CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
              <select value={newPriority} onChange={e => setNewPriority(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                <option value="HIGH">HIGH</option>
                <option value="MEDIUM">MEDIUM</option>
                <option value="LOW">LOW</option>
              </select>
              <button onClick={addTask}
                className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
                Add Task
              </button>
            </div>
          </div>

          <div className="bg-white rounded-lg border border-gray-200 p-5">
            <div className="grid grid-cols-1 lg:grid-cols-[1fr_auto_auto_auto_auto] gap-3">
              <input
                type="search"
                placeholder="Search task, issue, page URL, or recommendation..."
                value={search}
                onChange={e => setSearch(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500"
              />
              <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                {STATUS_FILTERS.map(status => <option key={status} value={status}>{status}</option>)}
              </select>
              <select value={priorityFilter} onChange={e => setPriorityFilter(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                {PRIORITY_FILTERS.map(priority => <option key={priority} value={priority}>{priority}</option>)}
              </select>
              <select value={modeFilter} onChange={e => setModeFilter(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                {MODE_FILTERS.map(mode => <option key={mode} value={mode}>{mode}</option>)}
              </select>
              <select value={categoryFilter} onChange={e => setCategoryFilter(e.target.value)}
                className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
                {categories.map(category => <option key={category} value={category}>{category}</option>)}
              </select>
            </div>
          </div>

          <div className="bg-white rounded-lg border border-gray-200 p-5">
            <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
              <div>
                <h2 className="text-sm font-semibold text-gray-900">Bulk Review Queue</h2>
                <p className="text-xs text-gray-500 mt-1">
                  {selectedTaskIds.size === 0
                    ? "Select automated or semi-automated tasks, generate fixes, review them, then mark done after applying."
                    : `${selectedTaskIds.size} selected: ${selectedAutomated} automated, ${selectedSemiAutomated} semi-automated, ${selectedManual} manual.`}
                </p>
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={() => selectTasksByMode("Automated")}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg border border-emerald-200 text-emerald-700 hover:bg-emerald-50 transition-colors">
                  Select Automated
                </button>
                <button onClick={() => selectTasksByMode("Semi-Automated")}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg border border-blue-200 text-blue-700 hover:bg-blue-50 transition-colors">
                  Select Semi-Automated
                </button>
                <button onClick={selectVisibleTasks}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors">
                  Select Visible
                </button>
                <button onClick={generateBulkReviewPlan} disabled={selectedTaskIds.size === 0}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-blue-600 text-white hover:bg-blue-700 disabled:opacity-50 transition-colors">
                  Generate Review Plan
                </button>
                <button onClick={markSelectedDone} disabled={selectedTaskIds.size === 0}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-green-600 text-white hover:bg-green-700 disabled:opacity-50 transition-colors">
                  Mark Selected Done
                </button>
                <button onClick={clearSelectedTasks} disabled={selectedTaskIds.size === 0}
                  className="px-3 py-1.5 text-xs font-semibold rounded-lg text-gray-600 hover:bg-gray-100 disabled:opacity-50 transition-colors">
                  Clear
                </button>
              </div>
            </div>

            {bulkReviewPlan && (
              <div className="mt-4 rounded-lg border border-blue-100 bg-blue-50 p-4">
                <div className="flex items-center justify-between gap-3 mb-3">
                  <p className="text-xs font-semibold uppercase text-blue-700">Selected Task Review Plan</p>
                  <button
                    onClick={() => navigator.clipboard?.writeText(bulkReviewPlan)}
                    className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-white border border-blue-200 text-blue-700 hover:bg-blue-50 transition-colors"
                  >
                    Copy Plan
                  </button>
                </div>
                <pre className="max-h-80 overflow-auto whitespace-pre-wrap text-xs leading-5 text-slate-800">{bulkReviewPlan}</pre>
              </div>
            )}
          </div>

          {loading ? <p className="text-gray-400 text-sm">Loading...</p> : (
            <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
              <div className="px-5 py-3 bg-gray-50 border-b border-gray-100 flex justify-between">
                <h2 className="text-sm font-semibold text-gray-700">Action Queue</h2>
                <span className="text-xs text-gray-500">{filteredTasks.length} visible</span>
              </div>
              {filteredTasks.length > 0 ? (
                <div className="divide-y divide-gray-100">
                  {filteredTasks.map(task => {
                    const expanded = expandedTaskId === task.id;
                    const generatedFix = generatedFixes[task.id];
                    const mode = taskMode(task);

                    return (
                      <div key={task.id} className={task.completed ? "bg-gray-50" : "bg-white"}>
                        <div className="px-5 py-4 flex flex-col gap-3 xl:flex-row xl:items-start">
                          <div className="flex items-start gap-3 flex-1 min-w-0">
                            <input
                              type="checkbox"
                              checked={selectedTaskIds.has(task.id)}
                              onChange={e => toggleSelectedTask(task.id, e.target.checked)}
                              className="w-4 h-4 mt-1 rounded text-blue-600 flex-shrink-0"
                              aria-label="Select task for bulk review"
                            />
                            <input
                              type="checkbox"
                              checked={task.completed}
                              onChange={e => toggleTask(task.id, e.target.checked)}
                              className="w-4 h-4 mt-1 rounded text-green-600 flex-shrink-0"
                            />
                            <div className="min-w-0">
                              <div className="flex flex-wrap items-center gap-2 mb-1">
                                <p className={`text-sm font-semibold ${task.completed ? "line-through text-gray-400" : "text-gray-900"}`}>{summarizeTask(task)}</p>
                                <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border ${PRIORITY_COLOR[task.priority] ?? PRIORITY_COLOR.LOW}`}>{task.priority}</span>
                                <span className={`text-xs font-semibold px-2 py-0.5 rounded-full border ${MODE_COLOR[mode]}`}>{mode}</span>
                                <span className="text-xs text-gray-500 bg-gray-100 rounded-full px-2 py-0.5">{task.category}</span>
                              </div>
                              {task.pageUrl && <p className="text-xs text-blue-700 break-all">{task.pageUrl}</p>}
                              <p className="text-xs text-gray-500 mt-1">{task.recommendation || task.task}</p>
                            </div>
                          </div>
                          <div className="flex flex-wrap gap-2 xl:justify-end">
                            <button
                              onClick={() => setExpandedTaskId(expanded ? null : task.id)}
                              className="px-3 py-1.5 text-xs font-semibold rounded-lg border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors"
                            >
                              {expanded ? "Hide Details" : "Details"}
                            </button>
                            <button
                              onClick={() => generateTaskFix(task)}
                              className="px-3 py-1.5 text-xs font-semibold rounded-lg bg-blue-600 text-white hover:bg-blue-700 transition-colors"
                            >
                              Generate Fix
                            </button>
                            <button
                              onClick={() => toggleTask(task.id, !task.completed)}
                              className={`px-3 py-1.5 text-xs font-semibold rounded-lg transition-colors ${task.completed ? "bg-white border border-gray-200 text-gray-700 hover:bg-gray-50" : "bg-green-600 text-white hover:bg-green-700"}`}
                            >
                              {task.completed ? "Reopen" : "Mark Done"}
                            </button>
                            <button onClick={() => deleteTask(task.id)} className="px-3 py-1.5 text-xs font-semibold rounded-lg text-red-600 hover:bg-red-50 transition-colors">
                              Delete
                            </button>
                          </div>
                        </div>

                        {expanded && (
                          <div className="mx-5 mb-4 rounded-lg border border-gray-200 bg-slate-50 p-4">
                            <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                              <div>
                                <p className="text-xs font-semibold uppercase text-gray-500 mb-2">Recommended workflow</p>
                                <p className={`inline-flex mb-3 text-xs font-semibold px-2 py-1 rounded-full border ${MODE_COLOR[mode]}`}>{mode}: {modeDescription(mode)}</p>
                                <ol className="list-decimal list-inside space-y-1 text-sm text-gray-700">
                                  <li>Open the page or website editor.</li>
                                  <li>Apply the suggested fix or recommendation.</li>
                                  <li>Re-run the site audit for verification.</li>
                                  <li>Mark this task as done after the issue is fixed.</li>
                                </ol>
                              </div>
                              <div>
                                <p className="text-xs font-semibold uppercase text-gray-500 mb-2">Suggested fix</p>
                                <div className="rounded-lg bg-white border border-gray-200 p-3 text-sm text-gray-800 whitespace-pre-wrap">
                                  {generatedFix || "Click Generate Fix to create a suggested action for this task."}
                                </div>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className="p-10 text-center text-gray-400">
                  <p className="font-medium text-gray-600">No matching tasks</p>
                  <p className="text-sm mt-1">Adjust filters or add a new task.</p>
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
