"use client";

import { useEffect, useState } from "react";

type Client = { id: string; businessName: string };
type Report = {
  client: { businessName: string; website: string | null; city: string | null; industry: string | null; napConsistent: boolean };
  gbpAudit: { score: number | null; reviewCount: number | null; rating: number | null; hasClaimed: boolean } | null;
  citations: { listed: boolean; napCorrect: boolean }[];
  seoTasks: { completed: boolean; category: string; priority: string }[];
  competitors: { name: string; mapRank: number | null; websiteRank: number | null; reviewCount: number | null; rating: number | null }[];
  rankEntries: { keyword: string; mapRank: number | null; websiteRank: number | null; recordedAt: string }[];
  reviewRequests: { status: string; createdAt: string }[];
  pageSpeed: { mobileScore: number | null; desktopScore: number | null; recordedAt: string } | null;
};

export default function AdminSeoReport() {
  const [clients, setClients] = useState<Client[]>([]);
  const [selectedClient, setSelectedClient] = useState("");
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetch("/api/admin/seo-report").then(r => r.json()).then(d => setClients(d.clients ?? []));
  }, []);

  useEffect(() => {
    if (!selectedClient) { setReport(null); return; }
    setLoading(true);
    fetch(`/api/admin/seo-report?clientId=${selectedClient}`)
      .then(r => r.json()).then(d => { setReport(d.report); setLoading(false); });
  }, [selectedClient]);

  if (loading) return <div className="p-8 text-gray-400">Generating report...</div>;

  const keywords = report ? [...new Set(report.rankEntries.map(e => e.keyword))] : [];

  return (
    <div>
      <div className="mb-6 flex flex-wrap items-center justify-between gap-4 print:hidden">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">SEO Report</h1>
          <p className="text-gray-500 mt-1">Full performance summary — print or share with client</p>
        </div>
        <div className="flex gap-3">
          <select value={selectedClient} onChange={e => setSelectedClient(e.target.value)}
            className="px-3 py-2 text-sm rounded-lg border border-gray-200 focus:outline-none focus:ring-2 focus:ring-blue-500">
            <option value="">Choose a client...</option>
            {clients.map(c => <option key={c.id} value={c.id}>{c.businessName}</option>)}
          </select>
          {report && (
            <button onClick={() => window.print()}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors">
              🖨 Print / Save PDF
            </button>
          )}
        </div>
      </div>

      {report && (
        <div className="space-y-6 print:space-y-4">
          {/* Header */}
          <div className="bg-blue-600 text-white rounded-2xl p-6 print:rounded-none print:p-4">
            <div className="flex justify-between items-start">
              <div>
                <p className="text-blue-200 text-sm font-medium">SEO Performance Report</p>
                <h2 className="text-2xl font-bold mt-1">{report.client.businessName}</h2>
                {report.client.city && <p className="text-blue-200 text-sm mt-1">{report.client.city}</p>}
              </div>
              <div className="text-right">
                <p className="text-blue-200 text-xs">Generated by</p>
                <p className="font-bold">BizAutomatrix</p>
                <p className="text-blue-200 text-xs mt-1">{new Date().toLocaleDateString()}</p>
              </div>
            </div>
          </div>

          {/* Score overview */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
            <ScoreTile label="GBP Score" value={report.gbpAudit?.score != null ? `${report.gbpAudit.score}%` : "—"} color="blue" />
            <ScoreTile label="Reviews" value={report.gbpAudit?.reviewCount?.toString() ?? "—"} color="yellow" />
            <ScoreTile label="Citations Listed" value={`${report.citations.filter(c => c.listed).length}/${report.citations.length}`} color="green" />
            <ScoreTile label="SEO Tasks Done" value={`${report.seoTasks.filter(t => t.completed).length}/${report.seoTasks.length}`} color="purple" />
          </div>

          {/* GBP + PageSpeed */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {report.gbpAudit && (
              <div className="bg-white rounded-2xl border border-gray-200 p-5">
                <h3 className="font-semibold text-gray-900 mb-3">Google Business Profile</h3>
                <div className="flex gap-6 text-sm">
                  <div><p className="text-gray-500">Claimed</p><p className="font-bold text-lg">{report.gbpAudit.hasClaimed ? "✓ Yes" : "✗ No"}</p></div>
                  <div><p className="text-gray-500">Score</p><p className="font-bold text-lg">{report.gbpAudit.score ?? "—"}%</p></div>
                  <div><p className="text-gray-500">Reviews</p><p className="font-bold text-lg">{report.gbpAudit.reviewCount ?? "—"}</p></div>
                  <div><p className="text-gray-500">Rating</p><p className="font-bold text-lg">{report.gbpAudit.rating ? `⭐ ${report.gbpAudit.rating}` : "—"}</p></div>
                </div>
              </div>
            )}
            {report.pageSpeed && (
              <div className="bg-white rounded-2xl border border-gray-200 p-5">
                <h3 className="font-semibold text-gray-900 mb-3">Site Speed</h3>
                <div className="flex gap-6 text-sm">
                  <div><p className="text-gray-500">Mobile</p><p className={`font-bold text-lg ${report.pageSpeed.mobileScore != null && report.pageSpeed.mobileScore >= 90 ? "text-green-600" : report.pageSpeed.mobileScore != null && report.pageSpeed.mobileScore >= 50 ? "text-yellow-600" : "text-red-600"}`}>{report.pageSpeed.mobileScore ?? "—"}/100</p></div>
                  <div><p className="text-gray-500">Desktop</p><p className={`font-bold text-lg ${report.pageSpeed.desktopScore != null && report.pageSpeed.desktopScore >= 90 ? "text-green-600" : report.pageSpeed.desktopScore != null && report.pageSpeed.desktopScore >= 50 ? "text-yellow-600" : "text-red-600"}`}>{report.pageSpeed.desktopScore ?? "—"}/100</p></div>
                </div>
              </div>
            )}
          </div>

          {/* Rank summary */}
          {keywords.length > 0 && (
            <div className="bg-white rounded-2xl border border-gray-200 p-5">
              <h3 className="font-semibold text-gray-900 mb-3">Keyword Rankings</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-xs text-gray-500 uppercase border-b border-gray-100">
                      <th className="text-left py-2">Keyword</th>
                      <th className="text-center py-2">Maps Rank</th>
                      <th className="text-center py-2">Web Rank</th>
                      <th className="text-right py-2">Last Updated</th>
                    </tr>
                  </thead>
                  <tbody>
                    {keywords.map(kw => {
                      const kwEntries = report.rankEntries.filter(e => e.keyword === kw).sort((a, b) => new Date(b.recordedAt).getTime() - new Date(a.recordedAt).getTime());
                      const latest = kwEntries[0];
                      return (
                        <tr key={kw} className="border-b border-gray-50">
                          <td className="py-2 text-gray-700">{kw}</td>
                          <td className="py-2 text-center font-semibold">{latest.mapRank ? `#${latest.mapRank}` : "—"}</td>
                          <td className="py-2 text-center font-semibold">{latest.websiteRank ? `#${latest.websiteRank}` : "—"}</td>
                          <td className="py-2 text-right text-gray-400 text-xs">{new Date(latest.recordedAt).toLocaleDateString()}</td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Competitors */}
          {report.competitors.length > 0 && (
            <div className="bg-white rounded-2xl border border-gray-200 p-5">
              <h3 className="font-semibold text-gray-900 mb-3">Competitor Comparison</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-xs text-gray-500 uppercase border-b border-gray-100">
                      <th className="text-left py-2">Competitor</th>
                      <th className="text-center py-2">Maps #</th>
                      <th className="text-center py-2">Web #</th>
                      <th className="text-center py-2">Reviews</th>
                      <th className="text-center py-2">Rating</th>
                    </tr>
                  </thead>
                  <tbody>
                    {report.competitors.map((c, i) => (
                      <tr key={i} className="border-b border-gray-50">
                        <td className="py-2 text-gray-700">{c.name}</td>
                        <td className="py-2 text-center">{c.mapRank ? `#${c.mapRank}` : "—"}</td>
                        <td className="py-2 text-center">{c.websiteRank ? `#${c.websiteRank}` : "—"}</td>
                        <td className="py-2 text-center">{c.reviewCount ?? "—"}</td>
                        <td className="py-2 text-center">{c.rating ? `⭐ ${c.rating}` : "—"}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {/* Review requests */}
          {report.reviewRequests.length > 0 && (
            <div className="bg-white rounded-2xl border border-gray-200 p-5">
              <h3 className="font-semibold text-gray-900 mb-3">Review Campaign</h3>
              <div className="grid grid-cols-3 gap-4 text-center text-sm">
                <div><p className="text-gray-500">Total Sent</p><p className="font-bold text-xl text-gray-900">{report.reviewRequests.filter(r => r.status === "SENT" || r.status === "CLICKED").length}</p></div>
                <div><p className="text-gray-500">Clicked</p><p className="font-bold text-xl text-green-600">{report.reviewRequests.filter(r => r.status === "CLICKED").length}</p></div>
                <div><p className="text-gray-500">Click Rate</p>
                  <p className="font-bold text-xl text-blue-600">
                    {report.reviewRequests.length > 0 ? Math.round((report.reviewRequests.filter(r => r.status === "CLICKED").length / report.reviewRequests.length) * 100) : 0}%
                  </p>
                </div>
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="text-center text-xs text-gray-400 py-4">
            Report generated by BizAutomatrix &mdash; {new Date().toLocaleDateString()}
          </div>
        </div>
      )}

      {!selectedClient && (
        <div className="bg-white rounded-2xl border border-gray-200 p-12 text-center text-gray-400">
          <p className="text-3xl mb-2">📋</p>
          <p className="font-medium text-gray-600">Select a client to generate their report</p>
        </div>
      )}
    </div>
  );
}

function ScoreTile({ label, value, color }: { label: string; value: string; color: string }) {
  const bg: Record<string, string> = { blue: "bg-blue-50 border-blue-100", yellow: "bg-yellow-50 border-yellow-100", green: "bg-green-50 border-green-100", purple: "bg-purple-50 border-purple-100" };
  const text: Record<string, string> = { blue: "text-blue-700", yellow: "text-yellow-700", green: "text-green-700", purple: "text-purple-700" };
  return (
    <div className={`rounded-2xl border p-4 text-center ${bg[color]}`}>
      <p className={`text-xs font-medium ${text[color]} mb-1`}>{label}</p>
      <p className={`text-2xl font-bold ${text[color]}`}>{value}</p>
    </div>
  );
}
